name: markdown validations

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**.md'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**.md'

jobs:
  javascript:    
    name: markdown validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g markdownlint-cli
      - run: markdownlint docs/
